[book]
title = "Spotiline Documentation"
authors = ["Muhammad Faeyza Ashira"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ejafee/spotiline"
